name: movieapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.2.2
  google_fonts: ^8.1.0
  json_serializable: ^6.13.2
  build_runner: ^2.15.0
  dio: ^5.9.2
  flutter_dotenv: ^6.0.1
  flutter_bloc: ^8.1.5
  google_nav_bar: ^5.0.7
  carousel_slider: ^5.1.2
  smooth_page_indicator: ^2.0.1
  intl: ^0.20.2
  share_plus: ^10.0.0
  animations: ^2.0.11
  json_annotation: any
  fpdart: ^1.2.0
  equatable: ^2.0.8

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#0d0d0d"
  image: assets/images/logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env